baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "systematik"

[[menu.main]]
    name = "Home"
    title = "Home"
    weight = 1
    identifier = "home"
    url = "/"
    
    [[menu.main]]
    name = "Dokumentation"
    title = "Dokumentation"
    weight = 2
    identifier = "dokumentation"
    url = "/dokumentation/"
    
    [[menu.main]]
    name = "Om"
    title = "Om"
    weight = 3
    identifier = "om"
    url = "/om/"
    
    